version : '2'
services:
  web:
    build: .
    ports:
      - "8081:80"
 #   links:
  #    - testsql
#    environment:
#      - MYSQL_DB_PASSWORD: root
  db:
    build: ./testsql
#    environment:
#      - MYSQL_ROOT_PASSWORD: root
  app:
    build: ./nginxtest
    ports:
      - "8082:80"
    volumes:
      - "/root/test: /etc/nginx/sites-available/default"

#networks:
#  default:
#    driver: custom-driver-1
